"""location

Revision ID: 0c73db33cd24
Revises: 2fa50c032dd1
Create Date: 2022-11-22 08:20:55.164492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c73db33cd24'
down_revision = '2fa50c032dd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
