"""company

Revision ID: 131dcef529ed
Revises: 9d92e6fe3f7a
Create Date: 2022-11-21 20:19:09.705696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131dcef529ed'
down_revision = '9d92e6fe3f7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
