"""location

Revision ID: 2fa50c032dd1
Revises: 4b92e90db970
Create Date: 2022-11-22 08:18:56.897351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa50c032dd1'
down_revision = '4b92e90db970'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
