"""new

Revision ID: 3285cee2033d
Revises: a25304d096b1
Create Date: 2022-11-23 00:47:43.337964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3285cee2033d'
down_revision = 'a25304d096b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procedures', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('procedures', 'duration')
    # ### end Alembic commands ###
