"""location

Revision ID: 4b92e90db970
Revises: 5f297a4d18c0
Create Date: 2022-11-22 07:50:21.719444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b92e90db970'
down_revision = '5f297a4d18c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placename', sa.String(), nullable=True),
    sa.Column('latitude', sa.Integer(), nullable=True),
    sa.Column('longitude', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_locations_placename'), 'locations', ['placename'], unique=True)
    op.add_column('workers', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_workers_location_id'), 'workers', ['location_id'], unique=False)
    op.create_foreign_key(None, 'workers', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workers', type_='foreignkey')
    op.drop_index(op.f('ix_workers_location_id'), table_name='workers')
    op.drop_column('workers', 'location_id')
    op.drop_index(op.f('ix_locations_placename'), table_name='locations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
