"""new

Revision ID: a3545a693f39
Revises: 3285cee2033d
Create Date: 2022-11-23 13:50:45.289278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3545a693f39'
down_revision = '3285cee2033d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    op.add_column('workers', sa.Column('schedule_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_workers_schedule_id'), 'workers', ['schedule_id'], unique=False)
    op.create_foreign_key(None, 'workers', 'schedules', ['schedule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workers', type_='foreignkey')
    op.drop_index(op.f('ix_workers_schedule_id'), table_name='workers')
    op.drop_column('workers', 'schedule_id')
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_table('schedules')
    # ### end Alembic commands ###
