"""new

Revision ID: aa4e79b518cb
Revises: a3545a693f39
Create Date: 2022-11-23 15:06:21.963529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa4e79b518cb'
down_revision = 'a3545a693f39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procedures', sa.Column('worker_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_procedures_worker_id'), 'procedures', ['worker_id'], unique=False)
    op.create_foreign_key(None, 'procedures', 'workers', ['worker_id'], ['id'])
    op.drop_column('procedures', 'specialization')
    op.add_column('schedules', sa.Column('worker_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_schedules_worker_id'), 'schedules', ['worker_id'], unique=False)
    op.create_foreign_key(None, 'schedules', 'workers', ['worker_id'], ['id'])
    op.drop_index('ix_workers_procedure_id', table_name='workers')
    op.drop_index('ix_workers_schedule_id', table_name='workers')
    op.drop_constraint('workers_schedule_id_fkey', 'workers', type_='foreignkey')
    op.drop_constraint('workers_procedure_id_fkey', 'workers', type_='foreignkey')
    op.drop_column('workers', 'schedule_id')
    op.drop_column('workers', 'procedure_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('procedure_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('workers', sa.Column('schedule_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('workers_procedure_id_fkey', 'workers', 'procedures', ['procedure_id'], ['id'])
    op.create_foreign_key('workers_schedule_id_fkey', 'workers', 'schedules', ['schedule_id'], ['id'])
    op.create_index('ix_workers_schedule_id', 'workers', ['schedule_id'], unique=False)
    op.create_index('ix_workers_procedure_id', 'workers', ['procedure_id'], unique=False)
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_index(op.f('ix_schedules_worker_id'), table_name='schedules')
    op.drop_column('schedules', 'worker_id')
    op.add_column('procedures', sa.Column('specialization', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'procedures', type_='foreignkey')
    op.drop_index(op.f('ix_procedures_worker_id'), table_name='procedures')
    op.drop_column('procedures', 'worker_id')
    # ### end Alembic commands ###
