"""worker

Revision ID: c6bc1dad81e0
Revises: 131dcef529ed
Create Date: 2022-11-21 20:35:33.372963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6bc1dad81e0'
down_revision = '131dcef529ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
