"""new

Revision ID: d29ac16eb013
Revises: aa4e79b518cb
Create Date: 2022-11-23 15:06:39.113180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd29ac16eb013'
down_revision = 'aa4e79b518cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
