"""location

Revision ID: dcd697e6317b
Revises: 0c73db33cd24
Create Date: 2022-11-22 08:29:10.882515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcd697e6317b'
down_revision = '0c73db33cd24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
